apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  namespace: default
  labels:
    app: web-test
    language: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - name: k8s-lab-test
        image: k8s-lab-test:v1
        ports:
          - containerPort: 2000
