apiVersion: v1
kind: Service
metadata:
  name: web-test
  namespace: default
  labels:
    app: web-test
spec:
  type: NodePort
  selector:
    app: web-test
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 2000
